#!/bin/sh -e

ROOT=`dirname $0`
INCOMING="$ROOT/incoming"
REPOSITORY="$ROOT/debian"
ARCHS="i386 amd64"

cd "$ROOT"

mkdir -p "$REPOSITORY/dists/unstable/main/source"
for arch in $ARCHS; do
  mkdir -p "$REPOSITORY/dists/unstable/main/binary-$arch"
  apt-ftparchive clean apt-ftparchive-$arch.conf
  apt-ftparchive generate apt-ftparchive-$arch.conf
done

apt-ftparchive -c=apt-release.conf release "$REPOSITORY/dists" > "$REPOSITORY/dists/unstable/Release"
#gpg --sign -ba -o "$REPOSITORY/dists/unstable/Release.gpg" "$REPOSITORY/dists/unstable/Release"

